name: CI
#on: [push, pull_request]
#  branches:
#    - main
on:
  pull_request:
    branches:
      - main
  push:

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      postgres-test:
        image: postgres
        env:
          POSTGRES_USER: test_pg_user
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_database

      redis-test:
        image: redis

      clickhouse-test:
        image: "clickhouse/clickhouse-server:23.8.2.7-alpine"

    outputs:
      traces_path: ${{ steps.traces.outputs.TRACES_PATH }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
      - name: Install dependencies
        run: |
          cp src/core/.env.ci src/core/.env
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Set TRACES_PATH
        id: traces
        run: |
          echo "TRACES_PATH=$(systemd-path temporary)/traces" >> ${GITHUB_OUTPUT}
      - name: Test with pytest
        run: |
          make test
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: traces
          path: ${{ steps.traces.outputs.TRACES_PATH }}
